# Generated by Django 5.1.6 on 2025-03-05 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="stripe_customer_id",
            field=models.CharField(
                blank=True, default="", help_text="Stripe customer ID", max_length=255
            ),
        ),
    ]
