# Generated by Django 5.1.7 on 2025-06-12 10:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("socialaccount", "0006_alter_socialaccount_extra_data"),
        ("users", "0003_user_tour_completed"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserGitHubAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "github_login",
                    models.CharField(help_text="GitHub username", max_length=255),
                ),
                (
                    "github_id",
                    models.CharField(help_text="GitHub user ID", max_length=50),
                ),
                (
                    "avatar_url",
                    models.URLField(blank=True, help_text="GitHub avatar URL"),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this is the user's primary GitHub account",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this GitHub account is active for the user",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "social_account",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_github_account",
                        to="socialaccount.socialaccount",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="github_accounts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User GitHub Account",
                "verbose_name_plural": "User GitHub Accounts",
                "unique_together": {
                    ("user", "github_login"),
                    ("user", "social_account"),
                },
            },
        ),
        migrations.CreateModel(
            name="GitHubAccountInstallation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("installation_id", models.CharField(max_length=100)),
                ("account_name", models.CharField(max_length=255)),
                (
                    "account_type",
                    models.CharField(
                        choices=[("user", "User"), ("organization", "Organization")],
                        max_length=50,
                    ),
                ),
                (
                    "permissions",
                    models.JSONField(default=dict, help_text="GitHub App permissions"),
                ),
                (
                    "repository_selection",
                    models.CharField(
                        choices=[("all", "All"), ("selected", "Selected")],
                        default="selected",
                        max_length=50,
                    ),
                ),
                ("installed_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user_github_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="app_installations",
                        to="users.usergithubaccount",
                    ),
                ),
            ],
            options={
                "verbose_name": "GitHub Account Installation",
                "verbose_name_plural": "GitHub Account Installations",
                "unique_together": {("user_github_account", "installation_id")},
            },
        ),
    ]
