# Generated by Django 5.1.7 on 2025-12-04 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_migrate_github_installations"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="usergithubaccount",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="usergithubaccount",
            name="social_account",
        ),
        migrations.RemoveField(
            model_name="usergithubaccount",
            name="user",
        ),
        migrations.DeleteModel(
            name="GitHubAccountInstallation",
        ),
        migrations.DeleteModel(
            name="UserGitHubAccount",
        ),
    ]
