# Generated by Django 5.1.7 on 2026-06-14 06:41

from django.db import migrations, models


def demote_duplicate_primaries(apps, schema_editor):
    """Ensure at most one primary GitHub account per user before adding the
    unique constraint (the prior save() logic was racy and could leave several).
    Keeps the most recently updated primary and demotes the rest (non-destructive).
    """
    UserGitHubAccount = apps.get_model("users", "UserGitHubAccount")
    seen_users = set()
    primaries = UserGitHubAccount.objects.filter(is_primary=True).order_by("user_id", "-updated_at")
    for account in primaries:
        if account.user_id in seen_users:
            account.is_primary = False
            account.save(update_fields=["is_primary"])
        else:
            seen_users.add(account.user_id)


class Migration(migrations.Migration):

    dependencies = [
        ("socialaccount", "0006_alter_socialaccount_extra_data"),
        ("users", "0005_migrate_github_installations"),
    ]

    operations = [
        migrations.RunPython(demote_duplicate_primaries, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name="usergithubaccount",
            index=models.Index(
                fields=["user", "is_active"], name="ugha_user_active_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usergithubaccount",
            index=models.Index(
                fields=["user", "is_primary"], name="ugha_user_primary_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="usergithubaccount",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_primary", True)),
                fields=("user",),
                name="unique_primary_github_account_per_user",
            ),
        ),
    ]
