name = "holly"
compatibility_date = "2025-08-12"

assets = { directory = "./build" }

[build]
  command = "npm run build"
  cwd = ""
  watch_dir = "src"

[git]
  # Disable submodule processing
  skip_submodules = true