# Generated by Django 5.1.7 on 2025-05-14 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("holly", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Knowledge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The name of the knowledge item",
                        max_length=64,
                        verbose_name="Name",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description of this knowledge item",
                        verbose_name="Description",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
            ],
            options={
                "verbose_name": "Knowledge",
                "verbose_name_plural": "Knowledge Items",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Tools",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The name of the MCP tool",
                        max_length=64,
                        verbose_name="Name",
                    ),
                ),
                ("config", models.JSONField()),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
            ],
            options={
                "verbose_name": "Tool",
                "verbose_name_plural": "Tools",
                "ordering": ["name"],
            },
        ),
        migrations.AlterModelOptions(
            name="llm",
            options={
                "ordering": ["name"],
                "verbose_name": "LLM",
                "verbose_name_plural": "LLMs",
            },
        ),
    ]
