# Generated by Django 5.1.7 on 2025-05-14 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("holly", "0002_knowledge_tools_alter_llm_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="tools",
            name="description",
            field=models.TextField(
                default="ddg£", help_text="Description of this MCP tool"
            ),
            preserve_default=False,
        ),
    ]
