# Generated by Django 5.1.7 on 2025-05-15 21:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("github_ext", "0010_githubappinstallation"),
        ("holly", "0003_tools_description"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Conversation",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Conversation",
                "verbose_name_plural": "Conversations",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("user", "User"), ("assistant", "Assistant")],
                        max_length=10,
                    ),
                ),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="holly.conversation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Message",
                "verbose_name_plural": "Messages",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="Mission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Mission title", max_length=255, verbose_name="Title"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Detailed description of the mission",
                        verbose_name="Description",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("aborted", "Aborted"),
                        ],
                        default="draft",
                        help_text="Current state of the mission",
                        max_length=20,
                        verbose_name="State",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "branch_name",
                    models.CharField(
                        help_text="Common branch name for all repositories in this mission",
                        max_length=255,
                        verbose_name="Branch Name",
                    ),
                ),
                (
                    "container_id",
                    models.CharField(
                        blank=True,
                        help_text="ID of the container for this mission",
                        max_length=64,
                        null=True,
                        verbose_name="Container ID",
                    ),
                ),
                (
                    "requirements",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Requirements for this mission in JSON format",
                        verbose_name="Requirements",
                    ),
                ),
                (
                    "collaborators",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Users who can collaborate on this mission",
                        related_name="collaborated_missions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "knowledge_items",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Knowledge items to provide context for this mission",
                        related_name="missions",
                        to="holly.knowledge",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        help_text="User who owns this mission",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owned_missions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "repositories",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Git repositories involved in this mission",
                        related_name="missions",
                        to="github_ext.repositorydetail",
                    ),
                ),
                (
                    "tools",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Tools available for this mission",
                        related_name="missions",
                        to="holly.tools",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mission",
                "verbose_name_plural": "Missions",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="MissionConversation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "conversation_id",
                    models.CharField(
                        help_text="ID of the conversation in the MCP system",
                        max_length=64,
                        verbose_name="Conversation ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Optional title for this conversation",
                        max_length=255,
                        verbose_name="Title",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "is_summarized",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this conversation has been summarized due to context window limits",
                        verbose_name="Is Summarized",
                    ),
                ),
                (
                    "summary",
                    models.TextField(
                        blank=True,
                        help_text="Summary of this conversation if it exceeded context limits",
                        verbose_name="Summary",
                    ),
                ),
                (
                    "remaining_tasks",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Tasks remaining after this conversation in JSON format",
                        verbose_name="Remaining Tasks",
                    ),
                ),
                (
                    "mission",
                    models.ForeignKey(
                        help_text="Mission this conversation belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversations",
                        to="holly.mission",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mission Conversation",
                "verbose_name_plural": "Mission Conversations",
                "ordering": ["-created_at"],
            },
        ),
    ]
