# Generated by Django 5.1.7 on 2025-05-19 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("holly", "0005_alter_message_conversation_alter_message_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="missionconversation",
            name="conversation_id",
            field=models.CharField(
                help_text="ID of the conversation in the MCP system",
                max_length=64,
                unique=True,
                verbose_name="Conversation ID",
            ),
        ),
    ]
