# Generated by Django 5.1.7 on 2025-05-20 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("holly", "0006_alter_missionconversation_conversation_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="llm",
            name="api_key",
            field=models.CharField(
                blank=True,
                help_text="The API key to use with this LLM",
                max_length=255,
                verbose_name="API Key",
            ),
        ),
        migrations.AddField(
            model_name="llm",
            name="base_url",
            field=models.URLField(
                blank=True,
                default="http://10.13.1.11:30000/v1",
                help_text="The base URL to use with this LLM",
                verbose_name="Base URL",
            ),
        ),
        migrations.AddField(
            model_name="llm",
            name="full_name",
            field=models.CharField(
                default="openai/qwen3:32b",
                help_text="The full name of the language learning model, eg openai/qwen3:32b",
                max_length=255,
                verbose_name="Full Name",
            ),
        ),
        migrations.AddField(
            model_name="llm",
            name="min_p",
            field=models.FloatField(
                blank=True,
                default=0.0,
                help_text="The min p value to use with this LLM",
                verbose_name="Min P",
            ),
        ),
        migrations.AddField(
            model_name="llm",
            name="temperature",
            field=models.FloatField(
                blank=True,
                default=0.7,
                help_text="The temperature value to use with this LLM",
                verbose_name="Temperature",
            ),
        ),
        migrations.AddField(
            model_name="llm",
            name="top_k",
            field=models.PositiveIntegerField(
                blank=True,
                default=20,
                help_text="The top k value to use with this LLM",
                verbose_name="Top K",
            ),
        ),
        migrations.AddField(
            model_name="llm",
            name="top_p",
            field=models.FloatField(
                blank=True,
                default=0.7,
                help_text="The top p value to use with this LLM",
                verbose_name="Top P",
            ),
        ),
        migrations.AddField(
            model_name="mission",
            name="llm",
            field=models.ForeignKey(
                blank=True,
                help_text="default LLM to use for this mission",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="holly.llm",
            ),
        ),
    ]
