# Generated by Django 5.1.7 on 2025-05-20 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("holly", "0007_llm_api_key_llm_base_url_llm_full_name_llm_min_p_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="missionconversation",
            index=models.Index(
                fields=["mission"], name="holly_missi_mission_a5fb42_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="missionconversation",
            index=models.Index(
                fields=["conversation_id"], name="holly_missi_convers_510269_idx"
            ),
        ),
    ]
