# Generated by Django 5.1.7 on 2025-05-23 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("holly", "0008_missionconversation_holly_missi_mission_a5fb42_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="llm",
            name="min_p",
            field=models.FloatField(
                blank=True,
                default=None,
                help_text="The min p value to use with this LLM",
                null=True,
                verbose_name="Min P",
            ),
        ),
        migrations.AlterField(
            model_name="llm",
            name="temperature",
            field=models.FloatField(
                blank=True,
                default=0.0,
                help_text="The temperature value to use with this LLM",
                verbose_name="Temperature",
            ),
        ),
        migrations.AlterField(
            model_name="llm",
            name="top_k",
            field=models.PositiveIntegerField(
                blank=True,
                default=None,
                help_text="The top k value to use with this LLM",
                null=True,
                verbose_name="Top K",
            ),
        ),
        migrations.AlterField(
            model_name="llm",
            name="top_p",
            field=models.FloatField(
                blank=True,
                default=None,
                help_text="The top p value to use with this LLM",
                null=True,
                verbose_name="Top P",
            ),
        ),
    ]
