# Generated by Django 5.1.7 on 2025-05-23 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("holly", "0009_alter_llm_min_p_alter_llm_temperature_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="llm",
            name="base_url",
            field=models.URLField(
                blank=True,
                default="http://10.13.1.11:30000/v1",
                help_text="The base URL to use with this LLM",
                null=True,
                verbose_name="Base URL",
            ),
        ),
    ]
