# Generated by Django 5.1.7 on 2025-05-23 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("holly", "0010_alter_llm_base_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="llm",
            name="max_tokens",
            field=models.IntegerField(
                blank=True,
                default=4096,
                help_text="The max output tokens for this model",
                null=True,
                verbose_name="MaxTokens",
            ),
        ),
    ]
