# Generated by Django 5.1.7 on 2025-05-23
from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings
from encrypted_fields.fields import EncryptedTextField


class Migration(migrations.Migration):

    dependencies = [
        ("holly", "0011_llm_max_tokens"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserLLMApiKey",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("api_key", EncryptedTextField(verbose_name="API Key")),
                (
                    "user",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="llm_api_keys", to=settings.AUTH_USER_MODEL),
                ),
                (
                    "llm",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="user_api_keys", to="holly.llm"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
            ],
            options={
                "verbose_name": "User LLM API Key",
                "verbose_name_plural": "User LLM API Keys",
                "unique_together": {("user", "llm")},
            },
        ),
        migrations.RemoveField(
            model_name="llm",
            name="api_key",
        ),
    ]
