# Generated by Django 5.1.7 on 2025-05-28 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("holly", "0012_move_api_key_to_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="knowledge",
            name="summary",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Summary of the knowledge",
                max_length=255,
                verbose_name="Summary",
            ),
        ),
        migrations.AlterField(
            model_name="userllmapikey",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
