# Generated by Django 5.1.7 on 2025-05-28 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("github_ext", "0014_remove_repositorydetail_branch_name"),
        ("holly", "0013_knowledge_summary_alter_userllmapikey_id"),
    ]

    operations = [
        # First remove the existing repositories field (drops the many-to-many table)
        migrations.RemoveField(
            model_name="mission",
            name="repositories",
        ),
        # Create the new MissionRepos model
        migrations.CreateModel(
            name="MissionRepos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "branch_name",
                    models.CharField(
                        help_text="Name of the branch from which to branch or create new branches from",
                        max_length=255,
                    ),
                ),
                (
                    "repository",
                    models.ForeignKey(
                        help_text="Name of repo attached to this mission",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="github_ext.repositorydetail",
                    ),
                ),
            ],
        ),
        # Add the repositories field back with the new relationship
        migrations.AddField(
            model_name="mission",
            name="repositories",
            field=models.ManyToManyField(
                blank=True,
                help_text="Git repositories involved in this mission",
                related_name="missions",
                to="holly.missionrepos",
            ),
        ),
    ]
