# Generated by Django 5.1.7 on 2025-06-01 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("holly", "0014_missionrepos_alter_mission_repositories"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="missionrepos",
            options={
                "verbose_name": "MissionRepos",
                "verbose_name_plural": "MissionRepos",
            },
        ),
    ]
