# Generated by Django 5.1.7 on 2025-06-01 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("holly", "0015_add_container_ip_address"),
        ("holly", "0015_alter_missionrepos_options"),
    ]

    operations = []
