# Generated by Django 5.1.7 on 2025-06-03 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("holly", "0016_merge_20250601_1840"),
        ("holly", "0016_merge_20250601_1853"),
    ]

    operations = []
