# Generated by Django 5.1.7 on 2025-10-13 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("holly", "0017_merge_20250603_0422"),
    ]

    operations = [
        migrations.AddField(
            model_name="mission",
            name="active_jobs",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of active async jobs",
                verbose_name="Active Jobs",
            ),
        ),
        migrations.AddField(
            model_name="mission",
            name="init_job_id",
            field=models.CharField(
                blank=True,
                help_text="ID of the container initialization job",
                max_length=64,
                null=True,
                verbose_name="Init Job ID",
            ),
        ),
        migrations.AlterField(
            model_name="mission",
            name="state",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("provisioning", "Provisioning"),
                    ("ready", "Ready"),
                    ("in_progress", "In Progress"),
                    ("completed", "Completed"),
                    ("aborted", "Aborted"),
                    ("error", "Error"),
                ],
                default="draft",
                help_text="Current state of the mission",
                max_length=20,
                verbose_name="State",
            ),
        ),
    ]
