# Generated by Django 5.1.7 on 2025-10-31 14:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("holly", "0018_mission_active_jobs_mission_init_job_id_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="mission",
            name="container_started_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the container was last started",
                null=True,
                verbose_name="Container Started At",
            ),
        ),
        migrations.AddField(
            model_name="mission",
            name="container_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("starting", "Starting"),
                    ("ready", "Ready"),
                    ("error", "Error"),
                    ("stopped", "Stopped"),
                ],
                help_text="Current status of the container",
                max_length=20,
                null=True,
                verbose_name="Container Status",
            ),
        ),
        migrations.AddField(
            model_name="mission",
            name="container_stopped_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the container was last stopped",
                null=True,
                verbose_name="Container Stopped At",
            ),
        ),
        migrations.AddField(
            model_name="missionconversation",
            name="error_message",
            field=models.TextField(
                blank=True,
                help_text="Error message if conversation failed",
                verbose_name="Error Message",
            ),
        ),
        migrations.AddField(
            model_name="missionconversation",
            name="last_activity_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Timestamp of last activity in this conversation",
                verbose_name="Last Activity At",
            ),
        ),
        migrations.AddField(
            model_name="missionconversation",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("completed", "Completed"),
                    ("error", "Error"),
                    ("archived", "Archived"),
                ],
                default="pending",
                help_text="Current status of this conversation",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("mission_ready", "Mission Ready"),
                            ("mission_error", "Mission Error"),
                            ("container_started", "Container Started"),
                            ("container_stopped", "Container Stopped"),
                            ("container_error", "Container Error"),
                            ("conversation_completed", "Conversation Completed"),
                            ("conversation_error", "Conversation Error"),
                            ("task_completed", "Task Completed"),
                            ("task_failed", "Task Failed"),
                            ("system_alert", "System Alert"),
                            ("info", "Information"),
                        ],
                        help_text="Type of notification",
                        max_length=50,
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="Notification title", max_length=255),
                ),
                ("message", models.TextField(help_text="Notification message content")),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("normal", "Normal"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="normal",
                        help_text="Notification priority level",
                        max_length=20,
                    ),
                ),
                (
                    "mission_id",
                    models.UUIDField(
                        blank=True,
                        help_text="Related mission ID if applicable",
                        null=True,
                    ),
                ),
                (
                    "conversation_id",
                    models.CharField(
                        blank=True,
                        help_text="Related conversation ID if applicable",
                        max_length=64,
                        null=True,
                    ),
                ),
                (
                    "data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional JSON data for the notification",
                    ),
                ),
                (
                    "read",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the notification has been read",
                    ),
                ),
                (
                    "read_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the notification was read",
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the notification was created"
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the notification expires (optional)",
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who receives this notification",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="holly_notif_user_id_8a7e57_idx",
                    ),
                    models.Index(
                        fields=["user", "read", "-created_at"],
                        name="holly_notif_user_id_b0075f_idx",
                    ),
                    models.Index(
                        fields=["mission_id"], name="holly_notif_mission_772bbe_idx"
                    ),
                    models.Index(
                        fields=["conversation_id"],
                        name="holly_notif_convers_289abc_idx",
                    ),
                ],
            },
        ),
    ]
