# Generated by Django 5.1.7 on 2025-11-23 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holly', '0019_mission_container_started_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('mission_ready', 'Mission Ready'), ('mission_error', 'Mission Error'), ('container_started', 'Container Started'), ('container_stopped', 'Container Stopped'), ('container_error', 'Container Error'), ('conversation_completed', 'Conversation Completed'), ('conversation_error', 'Conversation Error'), ('message_received', 'Message Received'), ('task_completed', 'Task Completed'), ('task_failed', 'Task Failed'), ('pr_created', 'Pull Request Created'), ('pr_failed', 'Pull Request Failed'), ('system_alert', 'System Alert'), ('info', 'Information')], help_text='Type of notification', max_length=50),
        ),
    ]
