# Generated by Django 5.1.7 on 2025-11-23 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("holly", "0020_add_user_ownership_to_llm"),
        ("holly", "0020_alter_notification_type"),
    ]

    operations = []
