# Generated by Django 5.1.7 on 2026-06-14 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("github_ext", "0016_alter_repositorydetail_github_id"),
        ("holly", "0021_merge_20251123_2016"),
    ]

    operations = [
        migrations.AddField(
            model_name="mission",
            name="metadata",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Additional mission metadata, e.g. the list of created pull requests",
                verbose_name="Metadata",
            ),
        ),
        migrations.AddField(
            model_name="mission",
            name="pull_request_number",
            field=models.IntegerField(
                blank=True,
                help_text="Number of the most recently created pull request",
                null=True,
                verbose_name="Pull Request Number",
            ),
        ),
        migrations.AddField(
            model_name="mission",
            name="pull_request_url",
            field=models.URLField(
                blank=True,
                default="",
                help_text="URL of the most recently created pull request",
                verbose_name="Pull Request URL",
            ),
        ),
        migrations.AddConstraint(
            model_name="missionrepos",
            constraint=models.UniqueConstraint(
                fields=("repository", "branch_name"), name="unique_repository_branch"
            ),
        ),
    ]
