# Generated by Django 5.1.7 on 2025-12-04 17:51

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("holly", "0021_merge_20251123_2016"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SlashCommand",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "is_system",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="System commands are available to all users",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Command name without the leading slash (e.g., 'summarize')",
                        max_length=100,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Command name can only contain letters, numbers, hyphens, and underscores",
                                regex="^[a-zA-Z0-9_-]+$",
                            )
                        ],
                    ),
                ),
                (
                    "command_type",
                    models.CharField(
                        choices=[
                            ("replacement", "String Replacement"),
                            ("function", "Python Function"),
                        ],
                        default="replacement",
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="User-friendly description of what the command does",
                    ),
                ),
                (
                    "replacement_text",
                    models.TextField(
                        blank=True,
                        help_text="Template text with {arg1}, {arg2} placeholders for replacement commands",
                    ),
                ),
                (
                    "function_path",
                    models.CharField(
                        blank=True,
                        help_text="Python import path (e.g., 'holly.holly.services.command_handlers.summarize_conversation')",
                        max_length=500,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Inactive commands won't be executed",
                    ),
                ),
                (
                    "usage_count",
                    models.IntegerField(
                        default=0, help_text="Track how often this command is used"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Owner of the command. NULL for system commands.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slash_commands",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "slash_commands",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["user", "name"], name="idx_user_name"),
                    models.Index(fields=["is_system", "name"], name="idx_system_name"),
                    models.Index(fields=["is_active", "name"], name="idx_active_name"),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("is_system", False), ("user__isnull", False)),
                            models.Q(("is_system", True), ("user__isnull", True)),
                            _connector="OR",
                        ),
                        name="system_command_no_user",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("command_type", "replacement"),
                                ("replacement_text__gt", ""),
                            ),
                            models.Q(("command_type", "replacement"), _negated=True),
                            _connector="OR",
                        ),
                        name="replacement_has_text",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("command_type", "function"), ("function_path__gt", "")
                            ),
                            models.Q(("command_type", "function"), _negated=True),
                            _connector="OR",
                        ),
                        name="function_has_path",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("user__isnull", False)),
                        fields=("user", "name"),
                        name="unique_user_command_name",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("is_system", True)),
                        fields=("name",),
                        name="unique_system_command_name",
                    ),
                ],
            },
        ),
    ]
