<script lang="ts">
  import { onDestroy } from "svelte";
  // Ensure the path is correct based on how @novnc/novnc structures its exports.
  // It's often under `core/rfb.js` or `lib/rfb.js`.
  // If you encounter "Cannot find module" errors, double-check your node_modules/@novnc/novnc directory.

  let vncWebSocketHost: string = "localhost";
  // This should be the port where websockify is running, typically the same port as the noVNC web UI.
  let vncWebSocketPort: number = 6901;
  let vncPassword: string = "vncpassword"; // Password for the actual VNC server

  let connectionStatus: string = "Disconnected";
  let rfbInstance: RFB | null = null;
  let screenElement: HTMLDivElement; // This div will host the canvas generated by RFB

  let showConnectionSettings: boolean = true;
  let connectionError: string | null = null;

  function connect() {
    connectionError = null;
    if (!screenElement) {
      connectionError =
        "Fatal Error: Screen container element not found in the DOM.";
      connectionStatus = connectionError;
      console.error(connectionError);
      return;
    }

    if (rfbInstance) {
      disconnect(); // Disconnect any existing session first
    }

    const webSocketUrl = `ws://${vncWebSocketHost}:${vncWebSocketPort}`;
    connectionStatus = `Connecting to ${webSocketUrl}...`;
    showConnectionSettings = false;
    console.log(`Attempting to connect RFB to: ${webSocketUrl}`);

    try {
      // The `target` is the HTML element where RFB will create and manage its canvas.
      // The `url` is the WebSocket endpoint for the VNC connection (websockify).
      // `credentials` are passed to the VNC server via websockify.
      rfbInstance = new RFB(screenElement, webSocketUrl, {
        credentials: { password: vncPassword },
      });

      // --- RFB Event Listeners ---
      rfbInstance.addEventListener("connect", () => {
        connectionStatus = `Connected to VNC via ${webSocketUrl}`;
        console.log("RFB Event: connect");
        // RFB automatically manages the canvas within screenElement
        // You might want to adjust focus or styles here
        if (rfbInstance && rfbInstance.remoteFocus) {
          rfbInstance.focus();
        }
      });

      rfbInstance.addEventListener("disconnect", (event: Event) => {
        // event.detail contains { clean: boolean, reason?: string }
        const reason = event.detail.reason
          ? ` Reason: ${event.detail.reason}`
          : "";
        connectionStatus = `Disconnected.${reason} (Clean: ${event.detail.clean})`;
        console.log(
          `RFB Event: disconnect - Clean: ${event.detail.clean}, Detail:`,
          event.detail,
        );
        rfbInstance = null; // Clear the instance
        // Do not set showConnectionSettings = true here, allow user to see disconnect message
        // User can click "Disconnect" button (which becomes "Show Settings") to go back
      });

      rfbInstance.addEventListener("credentialsrequired", () => {
        connectionStatus = "VNC server requires credentials.";
        console.log("RFB Event: credentialsrequired");
        // This typically means the password was wrong or not provided,
        // and the server is prompting again (though RFB usually handles the initial password).
        // You might want to prompt the user for password again if this happens.
        if (rfbInstance) {
          const newPassword = prompt("VNC Password Required:", vncPassword);
          if (newPassword) {
            vncPassword = newPassword; // Update the password for future attempts or if RFB allows resending
            rfbInstance.sendCredentials({ password: newPassword });
          } else {
            connectionStatus = "Credentials not provided. Disconnecting.";
            disconnect();
          }
        }
      });

      rfbInstance.addEventListener("securityfailure", (event: Event) => {
        connectionStatus = `Security failure: ${event.detail.reason || "Unknown reason"}`;
        console.error("RFB Event: securityfailure", event.detail);
        disconnect(); // Ensure cleanup
      });

      rfbInstance.addEventListener("onerror", (event: Event) => {
        // This is a more generic error handler if RFB itself encounters an issue.
        connectionStatus = `An error occurred: ${event.detail.error || "Unknown RFB error"}`;
        console.error("RFB Event: onerror", event.detail);
        // Consider if disconnect is appropriate here or if it's a non-fatal error.
      });

      // Add other event listeners as needed:
      // - 'desktopname': (event) => console.log('Desktop name:', event.detail.name)
      // - 'bell': () => console.log('VNC Bell received')
      // - 'clipboard': (event) => console.log('Clipboard from server:', event.detail.text)
    } catch (error: Event) {
      connectionError = `Failed to initialize RFB client: ${error.message}`;
      connectionStatus = connectionError;
      console.error(connectionError, error);
      showConnectionSettings = true; // Show settings again on critical init error
      rfbInstance = null;
    }
  }

  function disconnect() {
    connectionError = null;
    if (rfbInstance) {
      console.log("Disconnecting RFB instance...");
      rfbInstance.disconnect(); // This should trigger the 'disconnect' event listener
      rfbInstance = null; // Explicitly nullify
    }
    // Reset status, but wait for the disconnect event to confirm for a cleaner UX
    // connectionStatus = 'Disconnected';
    // showConnectionSettings = true; // This is handled by the "Show Settings / Disconnect" button logic now
  }

  function toggleSettings() {
    if (rfbInstance) {
      // If connected, this button acts as "Disconnect"
      disconnect();
      // The disconnect event will update status. We want to show settings after disconnect.
      // A small delay might be needed if the disconnect event is asynchronous and we want to ensure it fires first.
      setTimeout(() => {
        showConnectionSettings = true;
        connectionStatus = "Disconnected. Configure and connect again.";
      }, 100); // Give a moment for disconnect event processing
    } else {
      // If not connected, this button shows settings (or hides if already shown, though not the primary use)
      showConnectionSettings = !showConnectionSettings;
      if (!showConnectionSettings && !rfbInstance) {
        connectionStatus =
          'Connection panel hidden. Click "Connect" in settings.';
      } else {
        connectionStatus = "Disconnected. Configure and connect again.";
      }
    }
  }

  // Ensure disconnection when the component is destroyed
  onDestroy(() => {
    console.log("VncViewerCanvas: onDestroy called. Cleaning up RFB instance.");
    disconnect();
  });
</script>

<div class="vnc-canvas-container p-4">
  {#if showConnectionSettings}
    <div
      class="settings-panel mb-4 p-4 border dark:border-gray-700 rounded bg-white dark:bg-gray-800 dark:text-gray-100"
    >
      <h2 class="text-xl font-semibold mb-3 text-gray-700 dark:text-gray-200">
        VNC Connection (Direct via Canvas/WebSocket)
      </h2>
      {#if connectionError}
        <div
          class="mb-3 p-3 bg-red-100 text-red-700 border border-red-300 rounded-md"
        >
          Error: {connectionError}
        </div>
      {/if}
      <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
        <div>
          <label
            for="vncWebSocketHost"
            class="block text-sm font-medium text-gray-700 dark:text-gray-200 mb-1"
            >VNC WebSocket Host:</label
          >
          <input
            type="text"
            id="vncWebSocketHost"
            bind:value={vncWebSocketHost}
            class="w-full p-2 border border-gray-300 dark:bg-gray-900 dark:border-gray-800 rounded-md shadow-sm focus:ring-indigo-500 focus:border-indigo-500"
            placeholder="localhost"
          />
        </div>
        <div>
          <label
            for="vncWebSocketPort"
            class="block text-sm font-medium text-gray-700 dark:text-gray-200 mb-1"
            >VNC WebSocket Port (websockify):</label
          >
          <input
            type="number"
            id="vncWebSocketPort"
            bind:value={vncWebSocketPort}
            class="w-full p-2 border border-gray-300 dark:bg-gray-900 dark:border-gray-800 rounded-md shadow-sm focus:ring-indigo-500 focus:border-indigo-500"
            placeholder="6080"
          />
        </div>
        <div>
          <label
            for="vncPasswordCanvas"
            class="block text-sm font-medium text-gray-700 dark:text-gray-200 mb-1"
            >VNC Server Password:</label
          >
          <input
            type="password"
            id="vncPasswordCanvas"
            bind:value={vncPassword}
            class="w-full p-2 border border-gray-300 dark:bg-gray-900 dark:border-gray-800 rounded-md shadow-sm focus:ring-indigo-500 focus:border-indigo-500"
            placeholder="VNC Server Password"
          />
        </div>
      </div>
      <button
        on:click={connect}
        class="mt-4 w-full bg-theme-primry hover:bg-indigo-700 text-white font-bold py-2 px-4 rounded-md dark:bg-gray-900 dark:border-gray-800 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-opacity-50 transition duration-150 ease-in-out"
      >
        Connect
      </button>
    </div>
  {/if}

  <div class="status-and-controls mt-2 mb-2 flex justify-between items-center">
    <p class="text-sm text-gray-600 flex-grow">
      Status: <span class="font-semibold">{connectionStatus}</span>
    </p>
    <button
      on:click={toggleSettings}
      class="ml-4 bg-gray-300 hover:bg-gray-400 text-gray-800 font-semibold py-1 px-3 rounded-md text-sm focus:outline-none focus:ring-2 focus:ring-gray-500 focus:ring-opacity-50 transition duration-150 ease-in-out"
    >
      {#if rfbInstance}Disconnect{:else}Show/Hide Settings{/if}
    </button>
  </div>

  <!-- This div is the target for the RFB canvas -->
  <div
    bind:this={screenElement}
    id="vnc-screen"
    class="vnc-screen-area w-full h-[600px] border border-gray-400 bg-black rounded-md shadow-inner relative"
  >
    <!-- RFB will inject its canvas here. -->
    <!-- You can put placeholder content here if you want. -->
    {#if !rfbInstance && !showConnectionSettings}
      <div class="flex items-center justify-center h-full">
        <p class="text-gray-400">VNC Display Area</p>
      </div>
    {/if}
  </div>
</div>

<style>
  .vnc-canvas-container {
    min-height: 450px; /* Ensure container has some height */
  }
  .vnc-screen-area {
    /* The canvas injected by RFB will try to fill this. */
    /* Ensure it has defined dimensions. */
    /* RFB might also add styles for cursor handling etc. */
    position: relative; /* Important for RFB's internal canvas placement */
  }

  /* Styling for the canvas element that noVNC creates might be needed,
       or for the div that contains it if noVNC doesn't style it.
       By default, RFB creates a canvas that fills the target element. */
  :global(.vnc-screen-area canvas) {
    width: 100%;
    height: 100%;
  }
</style>
