# Generated by Django 5.1.6 on 2025-02-28 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("github_ext", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="repositorydetail",
            name="file_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="repositorydetail",
            name="file_tree",
            field=models.JSONField(blank=True),
        ),
    ]
