# Generated by Django 5.1.6 on 2025-02-28 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("github_ext", "0002_repositorydetail_file_count_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="repositorydetail",
            name="languages",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
