# Generated by Django 5.1.6 on 2025-02-28 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("github_ext", "0003_repositorydetail_languages"),
    ]

    operations = [
        migrations.AddField(
            model_name="repositorydetail",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="repositorydetail",
            name="forks_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="repositorydetail",
            name="size",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="repositorydetail",
            name="stargazers_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="repositorydetail",
            name="subscribers_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="repositorydetail",
            name="topics",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="repositorydetail",
            name="watchers_count",
            field=models.IntegerField(default=0),
        ),
    ]
