# Generated by Django 5.1.6 on 2025-02-28 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("github_ext", "0004_repositorydetail_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="repositorydetail",
            name="open_issues_count",
            field=models.IntegerField(default=0),
        ),
    ]
