# Generated by Django 5.1.6 on 2025-03-03 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("github_ext", "0005_repositorydetail_open_issues_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="repositorydetail",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
