# Generated by Django 5.1.6 on 2025-03-03 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("github_ext", "0006_alter_repositorydetail_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="repositorydetail",
            name="file_token_counts",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
