# Generated by Django 5.1.6 on 2025-03-05 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("github_ext", "0007_repositorydetail_file_token_counts"),
    ]

    operations = [
        migrations.AlterField(
            model_name="repositorydetail",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
    ]
