# Generated by Django 5.1.6 on 2025-03-07 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("github_ext", "0008_alter_repositorydetail_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="repositorydetail",
            name="private",
            field=models.BooleanField(default=True),
        ),
    ]
