# Generated by Django 5.1.6 on 2025-03-13 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("github_ext", "0009_repositorydetail_private"),
        ("socialaccount", "0006_alter_socialaccount_extra_data"),
    ]

    operations = [
        migrations.CreateModel(
            name="GitHubAppInstallation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("installation_id", models.CharField(max_length=100)),
                ("account_name", models.CharField(max_length=255)),
                (
                    "account_type",
                    models.CharField(
                        choices=[("user", "User"), ("organization", "Organization")],
                        max_length=50,
                    ),
                ),
                ("installed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "social_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="socialaccount.socialaccount",
                    ),
                ),
            ],
            options={
                "unique_together": {("social_account", "installation_id")},
            },
        ),
    ]
