# Generated by Django 5.1.7 on 2025-05-19 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("github_ext", "0010_githubappinstallation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="repositorydetail",
            name="repo",
            field=models.CharField(help_text="Repository name", max_length=255),
        ),
        migrations.AlterField(
            model_name="repositorydetail",
            name="username",
            field=models.CharField(
                help_text="GitHub username/organization", max_length=255
            ),
        ),
    ]
