# Generated by Django 5.1.7 on 2025-05-26 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("github_ext", "0011_alter_repositorydetail_repo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="repositorydetail",
            name="github_id",
            field=models.IntegerField(default=0, help_text="github repo id"),
        ),
    ]
