# Generated by Django 5.1.7 on 2025-05-26 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("github_ext", "0012_repositorydetail_github_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="repositorydetail",
            name="branch_name",
            field=models.CharField(
                default="main",
                help_text="Branch to use when forking or creating edits",
                max_length=200,
            ),
        ),
    ]
