# Generated by Django 5.1.7 on 2025-05-28 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("github_ext", "0013_repositorydetail_branch_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="repositorydetail",
            name="branch_name",
        ),
    ]
