# Generated by Django 5.1.7 on 2025-05-28 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("github_ext", "0014_remove_repositorydetail_branch_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="repositorydetail",
            name="github_id",
            field=models.IntegerField(
                default=0, help_text="github repo id", unique=True
            ),
        ),
    ]
