# Generated by Django 5.1.7 on 2025-06-01 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("github_ext", "0015_alter_repositorydetail_github_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="repositorydetail",
            name="github_id",
            field=models.CharField(
                default=0, help_text="github repo id", max_length=255, unique=True
            ),
        ),
    ]
