# Generated by Django 5.1.7 on 2026-06-15 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("github_ext", "0016_alter_repositorydetail_github_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="repositorydetail",
            name="file_tree",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="repositorydetail",
            name="github_id",
            field=models.CharField(
                help_text="github repo id", max_length=255, unique=True
            ),
        ),
    ]
