"""
Django settings for holly project.

Generated by 'django-admin startproject' using Django 5.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from datetime import timedelta
from pathlib import Path
from loguru import logger

import environ

from holly.middleware.exceptions import setup_logging

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent.parent
APPS_DIR = BASE_DIR / "holly"

# Read .env file
environ.Env.read_env(BASE_DIR / ".env")
env = environ.Env()
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool("DJANGO_DEBUG", False)

ALLOWED_HOSTS = env.list("DJANGO_ALLOWED_HOSTS", default=["localhost", "127.0.0.1"])

# Application definition

DJANGO_APPS = [
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.sites",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.admin",
    "django.forms",
    "django.contrib.sitemaps",
    "django.contrib.humanize",
]

THIRD_PARTY_APPS = [
    "anymail",
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "allauth.socialaccount.providers.github",
    "storages",
    "corsheaders",
    "ninja",
    "ninja_jwt",  # Added django-ninja-jwt
    "ninja_extra",
    "ninja_jwt.token_blacklist",
    "django_eventstream",
    "jsoneditor",
]

LOCAL_APPS = [
    "holly.users",
    "holly.github_ext",
    "holly.analytics",
    "holly.holly",
]

INSTALLED_APPS = DJANGO_APPS + THIRD_PARTY_APPS + LOCAL_APPS

MIDDLEWARE = [
    "holly.middleware.exceptions.LoguruExceptionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "holly.github_ext.middleware.oauth_session_enforcement",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "allauth.account.middleware.AccountMiddleware",
]

ROOT_URLCONF = "config.urls"

# Configuration for django-eventstream
EVENTSTREAM_ALLOW_ORIGIN = "*"

# MEDIA
# ------------------------------------------------------------------------------
# https://docs.djangoproject.com/en/dev/ref/settings/#media-root
MEDIA_ROOT = str(APPS_DIR / "media")
# https://docs.djangoproject.com/en/dev/ref/settings/#media-url
MEDIA_URL = "/media/"

# TEMPLATES
# ------------------------------------------------------------------------------
# https://docs.djangoproject.com/en/dev/ref/settings/#templates

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [str(APPS_DIR / "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.template.context_processors.i18n",
                "django.template.context_processors.media",
                "django.template.context_processors.static",
                "django.template.context_processors.tz",
                "django.contrib.messages.context_processors.messages",
                # "holly.users.context_processors.allauth_settings",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"
ASGI_APPLICATION = "config.asgi.application"

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    },
}

# AUTHENTICATION
# ------------------------------------------------------------------------------

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

PASSWORD_HASHERS = [
    # https://docs.djangoproject.com/en/dev/topics/auth/passwords/#using-argon2-with-django
    "django.contrib.auth.hashers.Argon2PasswordHasher",
    "django.contrib.auth.hashers.PBKDF2PasswordHasher",
    "django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher",
    "django.contrib.auth.hashers.BCryptSHA256PasswordHasher",
]

# https://docs.djangoproject.com/en/dev/ref/settings/#authentication-backends
AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
    "allauth.account.auth_backends.AuthenticationBackend",
]
# https://docs.djangoproject.com/en/dev/ref/settings/#auth-user-model
AUTH_USER_MODEL = "users.User"
# https://docs.djangoproject.com/en/dev/ref/settings/#login-redirect-url
LOGIN_REDIRECT_URL = "socialaccount_connections"
# https://docs.djangoproject.com/en/dev/ref/settings/#login-url
LOGIN_URL = "account_login"

# Allauth

ACCOUNT_LOGIN_METHODS = ["email"]
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_USER_MODEL_USERNAME_FIELD = None
ACCOUNT_EMAIL_VERIFICATION = "none"

SOCIALACCOUNT_ADAPTER = "holly.users.adapters.SocialAccountAdapter"

SOCIALACCOUNT_ONLY = True

SOCIALACCOUNT_STORE_TOKENS = True

SOCIALACCOUNT_PROVIDERS = {
    "github": {
        "VERIFIED_EMAIL": True,
        "SCOPE": [
            "user",
            "repo",
        ],
        "AUTH_PARAMS": {"access_type": "offline"},
        "APP": {
            "client_id": env.str("GITHUB_CLIENT_ID", default="dummy_client_id"),
            "secret": env.str("GITHUB_CLIENT_SECRET", default="dummy_secret"),
        },
    },
}

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

# https://docs.djangoproject.com/en/dev/ref/settings/#site-id
SITE_ID = 1

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "static/"
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"

STATICFILES_FINDERS = (
    "django.contrib.staticfiles.finders.FileSystemFinder",
    "django.contrib.staticfiles.finders.AppDirectoriesFinder",
)

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

INTERNAL_IPS = ["127.0.0.1"]

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# settings.py
CSRF_COOKIE_SECURE = True  # for HTTPS
CSRF_COOKIE_HTTPONLY = True  # Prevents JavaScript access to CSRF cookie
CSRF_USE_SESSIONS = True  # Optional: Store CSRF token in session instead of cookie
CSRF_TRUSTED_ORIGINS = env.list("DJANGO_CSRF_TRUSTED_ORIGINS", default=["https://localhost:5173"] if not DEBUG else ["http://localhost", "http://127.0.0.1"])


REPO_BASE_PATH = env.str("REPO_BASE_PATH", default=None)
REPO_BASE_PATH = Path(BASE_DIR, "tmp", "repo_clone") if REPO_BASE_PATH is None else Path(REPO_BASE_PATH)

TEST_CHAT_RESPONSES = env.bool("TEST_CHAT_RESPONSES", False)




# region stripe
STRIPE_WEBHOOK_SECRET = env.str("STRIPE_WEBHOOK_SECRET", default="dummy_webhook_secret")
STRIPE_SECRET_KEY = env.str("STRIPE_SECRET_KEY", default="dummy_secret_key")
STRIPE_PUBLIC_KEY = env.str("STRIPE_PUBLIC_KEY", default="dummy_public_key")

# endregion

SECRET_KEY = env.str("SECRET_KEY", default="dummy_secret_auth_key")


# region Warnings for missing environment variables
FORMS_URLFIELD_ASSUME_HTTPS = (
    True  # RemovedInDjango60Warning: The `url` argument to `URLField` is deprecated. Set `url_field` to `True` instead.
)

# endregion

# region logging

DJANGO_ERROR_LOGS = env.str("DJANGO_ERROR_LOGS", default="./tmp/holly.log")

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
        },
    },
    "loggers": {
        "allauth": {
            "handlers": ["console"],
            "level": "DEBUG",
        },
    },
}

setup_logging(error_log_path=DJANGO_ERROR_LOGS)
# endregion

# region llm
LLM_ENABLED = env.bool("LLM_ENABLED", True)
GEMINI_API_KEY = env.str("GEMINI_API_KEY", "")
GEMINI_API_KEYS = env.list("GEMINI_API_KEYS", default=[])
# endregion

# region api
API_KEY = env.str("API_KEY", "test_api_key")  # Default value only for development

# Import REST MCP settings
from .mcp import *

# endregion


# region GitHub Apps
GITHUB_APP_NAME = env.str("GITHUB_APP_NAME", default="")
GITHUB_APP_ID = env.str("GITHUB_APP_ID", default="dummy_app_id")
GITHUB_CLIENT_ID = env.str("GITHUB_CLIENT_ID", default="dummy_client_id")
GITHUB_CLIENT_SECRET = env.str("GITHUB_CLIENT_SECRET", default="dummy_secret")
GITHUB_APP_PRIVATE_KEY_PATH = env.str("GITHUB_APP_PRIVATE_KEY_PATH", default="")

# GitHub App webhook configuration
GITHUB_WEBHOOK_SECRET = env.str("GITHUB_WEBHOOK_SECRET", default="")

# Validate GitHub App configuration in production
if not DEBUG and GITHUB_APP_NAME and GITHUB_CLIENT_ID != "dummy_client_id":
    from pathlib import Path
    key_path = Path(GITHUB_APP_PRIVATE_KEY_PATH) if GITHUB_APP_PRIVATE_KEY_PATH else None
    if not key_path or not key_path.exists():
        logger.warning(f"GitHub App private key not found at {GITHUB_APP_PRIVATE_KEY_PATH}")
# endregion


# region Code Editor settings


from .code_editor import *  # noqa: F403, E402
from .holly import *  # noqa: F403, E402

# endregion

# region Celery Configuration
# Celery settings with RabbitMQ as broker and Redis as result backend
CELERY_BROKER_URL = env.str("CELERY_BROKER_URL", default="amqp://guest:guest@localhost:5672//")
CELERY_REDIS_PASSWORD = env.str("CELERY_REDIS_PASSWORD", default="")
CELERY_RESULT_BACKEND = env.str("CELERY_RESULT_BACKEND", default=f"redis://{CELERY_REDIS_PASSWORD}@localhost:6379/2")
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = TIME_ZONE
CELERY_ENABLE_UTC = True

# Task execution settings
CELERY_TASK_SOFT_TIME_LIMIT = 600  # 10 minutes soft limit
CELERY_TASK_TIME_LIMIT = 900  # 15 minutes hard limit

# Result backend settings for django-celery-results
CELERY_RESULT_EXTENDED = True
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_SEND_SENT_EVENT = True

# Add django-celery-results to installed apps if not already there
if "django_celery_results" not in INSTALLED_APPS:
    INSTALLED_APPS = [*INSTALLED_APPS, "django_celery_results"]
# endregion

# region django-fernet-encrypted-fields
SALT_KEY = [env.str("SALT_KEY", "f2fa786c-021c-4103-acdf-82cea504eaae")]

# endregion

# region django-jsoneditor
JSON_EDITOR_JS = "https://cdnjs.cloudflare.com/ajax/libs/jsoneditor/8.6.4/jsoneditor.js"
JSON_EDITOR_CSS = "https://cdnjs.cloudflare.com/ajax/libs/jsoneditor/8.6.4/jsoneditor.css"
# endregion

# region Frontend URL
# Frontend URL - use https://getholly.ai for production, localhost for development
FRONTEND_URL = env.str("FRONTEND_URL", default="http://localhost:5173")
# endregion

# region Email Configuration (Development)
EMAIL_BACKEND = env.str("DJANGO_EMAIL_BACKEND", default="django.core.mail.backends.console.EmailBackend")
DEFAULT_FROM_EMAIL = env.str("DJANGO_DEFAULT_FROM_EMAIL", default="webmaster@localhost")
# endregion


# region Ninja-jwt
NINJA_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=5),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
    "ROTATE_REFRESH_TOKENS": False,
    "BLACKLIST_AFTER_ROTATION": False,
    "UPDATE_LAST_LOGIN": False,
    "ALGORITHM": "HS256",
    "SIGNING_KEY": SECRET_KEY,
    "VERIFYING_KEY": None,
    "AUDIENCE": None,
    "ISSUER": None,
    "JWK_URL": None,
    "LEEWAY": 0,
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
    "USER_AUTHENTICATION_RULE": "ninja_jwt.authentication.default_user_authentication_rule",
    "AUTH_TOKEN_CLASSES": ("ninja_jwt.tokens.AccessToken",),
    "TOKEN_TYPE_CLAIM": "token_type",
    "TOKEN_USER_CLASS": "ninja_jwt.models.TokenUser",
    "JTI_CLAIM": "jti",
    "SLIDING_TOKEN_REFRESH_EXP_CLAIM": "refresh_exp",
    "SLIDING_TOKEN_LIFETIME": timedelta(minutes=5),
    "SLIDING_TOKEN_REFRESH_LIFETIME": timedelta(days=1),
    # For Controller Schemas
    # FOR OBTAIN PAIR
    "TOKEN_OBTAIN_PAIR_INPUT_SCHEMA": "ninja_jwt.schema.TokenObtainPairInputSchema",
    "TOKEN_OBTAIN_PAIR_REFRESH_INPUT_SCHEMA": "ninja_jwt.schema.TokenRefreshInputSchema",
    # FOR SLIDING TOKEN
    "TOKEN_OBTAIN_SLIDING_INPUT_SCHEMA": "ninja_jwt.schema.TokenObtainSlidingInputSchema",
    "TOKEN_OBTAIN_SLIDING_REFRESH_INPUT_SCHEMA": "ninja_jwt.schema.TokenRefreshSlidingInputSchema",
    "TOKEN_BLACKLIST_INPUT_SCHEMA": "ninja_jwt.schema.TokenBlacklistInputSchema",
    "TOKEN_VERIFY_INPUT_SCHEMA": "ninja_jwt.schema.TokenVerifyInputSchema",
}

# endregion
