# Generated by Django 5.1.7 on 2025-03-28 14:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Repository",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "username",
                    models.CharField(max_length=100, verbose_name="Repository Owner"),
                ),
                (
                    "repo_name",
                    models.CharField(max_length=100, verbose_name="Repository Name"),
                ),
                ("private", models.BooleanField(default=True, verbose_name="Private")),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="Timestamp"),
                ),
            ],
            options={
                "verbose_name": "Repository Model",
                "verbose_name_plural": "Repository Models",
                "ordering": ("-timestamp",),
                "indexes": [
                    models.Index(
                        fields=["username", "repo_name"],
                        name="analytics_r_usernam_c7392c_idx",
                    ),
                    models.Index(
                        fields=["timestamp"], name="analytics_r_timesta_950f41_idx"
                    ),
                ],
                "unique_together": {("username", "repo_name")},
            },
        ),
        migrations.CreateModel(
            name="LLMQuery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("query_text", models.TextField(verbose_name="Query Text")),
                (
                    "model_name",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=250,
                        verbose_name="Model Name",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="Timestamp"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="llm_queries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "repo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="queries",
                        to="analytics.repository",
                    ),
                ),
            ],
            options={
                "verbose_name": "LLM Query",
                "verbose_name_plural": "LLM Queries",
                "ordering": ("-timestamp",),
                "indexes": [
                    models.Index(
                        fields=["repo"], name="analytics_l_repo_id_f95694_idx"
                    ),
                    models.Index(
                        fields=["user"], name="analytics_l_user_id_418ce3_idx"
                    ),
                    models.Index(
                        fields=["model_name"], name="analytics_l_model_n_d49ba0_idx"
                    ),
                    models.Index(
                        fields=["timestamp"], name="analytics_l_timesta_51fd67_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="RepoView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="Timestamp"),
                ),
                (
                    "repo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="views",
                        to="analytics.repository",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="repo_views",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Repository View",
                "verbose_name_plural": "Repository Views",
                "ordering": ("-timestamp",),
                "indexes": [
                    models.Index(
                        fields=["repo"], name="analytics_r_repo_id_a704d6_idx"
                    ),
                    models.Index(
                        fields=["user"], name="analytics_r_user_id_e1ab42_idx"
                    ),
                    models.Index(
                        fields=["timestamp"], name="analytics_r_timesta_72827b_idx"
                    ),
                ],
            },
        ),
    ]
